# config.yml

display_url: https://thebell-portfolio.netlify.app
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'configuration'
    label: 'Global Configuration'
    editor:
      preview: false
    files:
      - label: "General"
        name: "general"
        file: "site/_data/general_settings.yml"
        fields: 
          - { label: Title, name: title, widget: string, hint: 'Website title.' }
          - { label: Description, name: description, widget: string, hint: 'Website description for SEO.' }
          - { label: Social Media on Topnav, name: social_media_on_topnav, widget: boolean, hint: 'If enabled, social icons will be displayed in the top right.' }
          - { label: Social Share Image, name: social_media_share_image, widget: image, choose_url: true, hint: 'When sharing this website this image will be used.' }
          - { label: Footer, name: footer, widget: string, hint: 'Footer can be white or dark.' }
          - { label: Disqus ID, name: disqus-identifier, required: false, widget: string }
          - { label: Google Analytics ID , name: google-analytics, required: false, widget: string }
      - label: "Homepage"
        name: "home"
        file: "site/_data/home.yml"
        fields: 
          - { label: Title, name: title, widget: string, hint: 'Hero title.' }
          - { label: Description, name: description_html, widget: string, hint: 'Description under the hero title.' }
          - { label: Hero Image, name: image, widget: image, choose_url: true, hint: 'Image used for the Hero' }
          - { label: Image Alt, name: description_html, widget: string, hint: 'Image description' }
          - { label: Main CTA Text, name: cta_button, widget: string, hint: 'Button text for main CTA' }
          - { label: Main CTA Link, name: cta_button_link, widget: string, hint: 'Link for main CTA' }
          - { label: Secondary CTA Text, name: works_button, widget: string, hint: 'Button text for secondary CTA' }
          - { label: Secondary CTA Link, name: works_button_link, widget: string, hint: 'Link for secondary CTA' }
      - label: "Navigation"
        name: "navigation"
        file: "site/_data/navigation.yml"
        fields:
          - label: "Navigation Menu"
            name: "menu__items"
            widget: "list"
            collapse: false
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Link, name: url, widget: string }
      - label: "Social Links"
        name: "social"
        file: "site/_data/social_links.yml"
        fields:
          - label: "Social Links"
            name: "social"
            widget: "list"
            collapse: false
            fields:
              - { label: Name, name: icon, widget: string }
              - { label: Link, name: link, widget: string }
      - label: "Contact Section"
        name: ''
        file: "site/_data/contact.yml"
        fields:
          - { label: Name, name: form_title, widget: string }
          - { label: Description, name: form_description, widget: string }
          - { label: Email, name: form_submission_email, widget: string }
          - { label: Button Text, name: form_button_text, widget: string }
  - name: 'pages'
    label: 'Pages'
    folder: 'site/collections/_pages/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'content_blocks Date', name: 'date', widget: 'datetime' }
  - name: 'projects'
    label: 'Projects'
    folder: 'site/collections/_projects/'
    create: true
    sortable_fields: ['commit_date', 'filename', 'title', 'published']
    view_filters:
      - label: Drafts
        field: published
        pattern: false
      - label: Published
        field: published
        pattern: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: '_project' }
      - { label: 'Published', name: 'published', widget: 'boolean', hint: 'Enable this checkbox to publish the project so that it is visible', default: true}
      - { label: 'Title', name: 'title', hint: 'Title that will be displayed for this project', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', hint: 'Text under the project title', widget: 'string' }
      - { label: 'Description', name: 'description', hint: 'Description for SEO purposes', widget: 'string' }
      - { label: 'Cover Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      