# config.yml

display_url: https://thebell-portfolio.netlify.app
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'configuration'
    label: 'Global Site Configuration'
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "menu__settings"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Menu"
            name: "menu__items"
            widget: "list"
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Link, name: url, widget: string }
      - label: "Social Links"
        name: "social"
        file: "_data/social_links.yml"
        fields:
          - label: "Social Links"
            name: "items"
            widget: "list"
            fields:
              - { label: Name, name: icon, widget: string }
              - { label: Link, name: link, widget: string }
      - label: "Contact Section"
        name: ''
        file: "_data/contact.yml"
        fields:
          - { label: Name, name: form_title, widget: string }
          - { label: Description, name: form_description, widget: string }
          - { label: Email, name: form_submission_email, widget: string }
          - { label: Button Text, name: form_button_text, widget: string }
  - name: 'pages'
    label: 'Pages'
    folder: 'site/collections/_pages/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'content_blocks Date', name: 'date', widget: 'datetime' }
  - name: 'projects'
    label: 'Projects'
    folder: 'site/collections/_projects/'
    create: true
    sortable_fields: ['commit_date', 'filename', 'title', 'published']
    view_filters:
      - label: Drafts
        field: published
        pattern: false
      - label: Published
        field: published
        pattern: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: '_project' }
      - { label: 'Published', name: 'published', widget: 'boolean', hint: 'Enable this checkbox to publish the project so that it is visible', default: true}
      - { label: 'Title', name: 'title', hint: 'Title that will be displayed for this project', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', hint: 'Text under the project title', widget: 'string' }
      - { label: 'Description', name: 'description', hint: 'Description for SEO purposes', widget: 'string' }
      - { label: 'Cover Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      